import { ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Text } from '#/components/ui/text';
import { getReferrals } from '#/core/database/estate';

export default function Referrals() {
  const router = useRouter();
  const referrals = getReferrals();
  return <ScrollView style={s.page} contentContainerStyle={s.content}><TouchableOpacity onPress={() => router.back()}><Text style={s.back}>‹ Back</Text></TouchableOpacity><Text style={s.eyebrow}>REFERRALS</Text><Text style={s.title}>Your referral dashboard</Text><Text style={s.subtitle}>Track the people you’ve connected with Neup.Estate.</Text><View style={s.stats}><View><Text style={s.number}>{referrals.length}</Text><Text style={s.caption}>Leads referred</Text></View><View><Text style={s.number}>0</Text><Text style={s.caption}>Converted</Text></View><View><Text style={s.number}>NPR 0</Text><Text style={s.caption}>Rewards</Text></View></View><TouchableOpacity style={s.primary} onPress={() => router.push('/referrals/create')}><Text style={s.primaryText}>Create a referral  →</Text></TouchableOpacity><Text style={s.section}>Leads referred by Me</Text>{referrals.length ? referrals.map((lead) => <TouchableOpacity key={lead.id} style={s.card} onPress={() => router.push(`/referrals/${lead.id}`)}><View style={s.copy}><Text style={s.name}>{lead.personName}</Text><Text style={s.detail}>{lead.requirement}</Text><Text style={s.date}>{new Date(lead.createdOn).toLocaleDateString()}</Text></View><Text style={s.chevron}>›</Text></TouchableOpacity>) : <Text style={s.empty}>No referrals yet.</Text>}</ScrollView>;
}
const s = StyleSheet.create({ page:{flex:1,backgroundColor:'#f4f7fb'},content:{padding:20,paddingTop:62,paddingBottom:40},back:{color:'#3975b5',fontWeight:'700',marginBottom:34},eyebrow:{color:'#5c84b5',fontSize:11,fontWeight:'800',letterSpacing:1.8},title:{color:'#163a63',fontSize:29,fontWeight:'800',marginTop:12},subtitle:{color:'#82908a',fontSize:14,lineHeight:21,marginTop:8},stats:{backgroundColor:'#fff',borderRadius:18,padding:18,marginTop:24,flexDirection:'row',justifyContent:'space-between'},number:{color:'#3975b5',fontSize:22,fontWeight:'800'},caption:{color:'#82908a',fontSize:11,marginTop:4},primary:{backgroundColor:'#3975b5',borderRadius:14,paddingVertical:15,alignItems:'center',marginTop:16},primaryText:{color:'#fff',fontWeight:'800'},section:{color:'#163a63',fontSize:18,fontWeight:'800',marginTop:30,marginBottom:12},card:{backgroundColor:'#fff',borderRadius:14,padding:16,marginBottom:10,flexDirection:'row',alignItems:'center'},copy:{flex:1},name:{color:'#163a63',fontSize:15,fontWeight:'800'},detail:{color:'#66809a',fontSize:12,marginTop:5},date:{color:'#9aabbc',fontSize:11,marginTop:7},chevron:{color:'#9aabbc',fontSize:25},empty:{color:'#82908a',marginTop:8}});
