import { StatusBar } from 'expo-status-bar';
import { useRouter } from 'expo-router';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, TextInput, TouchableOpacity, View } from 'react-native';
import { Text } from '#/components/ui/text';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function SignIn() { const router=useRouter(); return <SafeAreaView style={s.page}><StatusBar style="dark" /><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView contentContainerStyle={{ flexGrow: 1 }} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>‹</Text></TouchableOpacity><View style={s.body}><Text style={s.eyebrow}>WELCOME BACK</Text><Text style={s.title}>Sign in to Neup.Estate</Text><Text style={s.subtitle}>Pick up where you left off.</Text><TextInput style={s.input} placeholder="Email address" placeholderTextColor="#9aa6a2" keyboardType="email-address" autoCapitalize="none" /><TextInput style={s.input} placeholder="Password" placeholderTextColor="#9aa6a2" secureTextEntry /><TouchableOpacity style={s.primary}><Text style={s.primaryText}>Sign in</Text></TouchableOpacity><Text style={s.switch}>Don’t have an account? <Text style={s.link} onPress={()=>router.push('/auth/signup')}>Create one</Text></Text></View></ScrollView></KeyboardAvoidingView></SafeAreaView>; }

const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f6f7f9',padding:20},back:{fontSize:36,color:'#173d35'},body:{marginTop:58},eyebrow:{color:'#557d54',fontSize:11,fontWeight:'800',letterSpacing:1.5},title:{color:'#173d35',fontSize:29,fontWeight:'900',marginTop:10},subtitle:{color:'#71817b',fontSize:14,marginTop:8,marginBottom:28},input:{height:54,backgroundColor:'#fff',borderRadius:14,paddingHorizontal:16,color:'#173d35',fontSize:14,marginBottom:12},primary:{backgroundColor:'#173d35',borderRadius:14,paddingVertical:16,alignItems:'center',marginTop:10},primaryText:{color:'#d8f36a',fontWeight:'800',fontSize:15},switch:{color:'#71817b',textAlign:'center',fontSize:13,marginTop:22},link:{color:'#557d54',fontWeight:'800'}});
