import { Image, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';

const data = {
  recents: { title: 'Recently viewed', subtitle: 'Homes you’ve looked at lately', items: [['A quiet modern retreat in the heart of the city.', 'Austin, Texas', '$1,240,000', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&q=85'], ['Sunlight, space, and room to make it yours.', 'Scottsdale, Arizona', '$895,000', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=700&q=85']] },
  saved: { title: 'Saved homes', subtitle: 'Your shortlist, all in one place', items: [['A warm, thoughtful home made for slow mornings.', 'Nashville, Tennessee', '$760,000', 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=700&q=85'], ['A quiet modern retreat in the heart of the city.', 'Austin, Texas', '$1,240,000', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&q=85']] },
  visits: { title: 'Your visits', subtitle: 'Upcoming and past property tours', items: [['1801 Vista Lane', 'Tomorrow · 10:30 AM', 'Confirmed', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&q=85'], ['Maple Street bungalow', 'Aug 24 · 2:00 PM', 'Completed', 'https://images.unsplash.com/photo-1494526585095-c41746248156?w=700&q=85']] },
};

export default function ProfileList({ type }: { type: keyof typeof data }) {
  const router = useRouter(); const page = data[type];
  return <View style={s.page}><View style={s.header}><TouchableOpacity onPress={() => router.back()}><Text style={s.back}>‹</Text></TouchableOpacity><View><Text style={s.title}>{page.title}</Text><Text style={s.subtitle}>{page.subtitle}</Text></View><View style={{ width: 28 }} /></View><ScrollView contentContainerStyle={s.content}>{page.items.map((item, i) => <TouchableOpacity key={item[0]} style={s.card}><Image source={{ uri: item[3] }} style={s.image} /><View style={s.info}><Text style={s.itemTitle}>{item[0]}</Text><Text style={s.location}>⌖  {item[1]}</Text><Text style={[s.value, type === 'visits' && s.confirmed]}>{type === 'visits' ? item[2] : item[2]}</Text></View><Text style={s.chevron}>›</Text></TouchableOpacity>)}{page.items.length === 0 && <Text style={s.empty}>Nothing here yet.</Text>}</ScrollView></View>;
}

const s = StyleSheet.create({ page: { flex: 1, backgroundColor: '#f6f7f9' }, header: { height: 105, paddingTop: 43, paddingHorizontal: 20, backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', gap: 14, elevation: 12, shadowColor: '#173d35', shadowOffset: { width: 0, height: 6 }, shadowOpacity: .24, shadowRadius: 12 }, back: { color: '#173d35', fontSize: 35, lineHeight: 30 }, title: { color: '#173d35', fontSize: 17, fontWeight: '800' }, subtitle: { color: '#8b9994', fontSize: 11, marginTop: 3 }, content: { padding: 20, paddingBottom: 35 }, card: { backgroundColor: '#fff', borderRadius: 16, marginBottom: 14, overflow: 'hidden', flexDirection: 'row', alignItems: 'center', padding: 10 }, image: { width: 94, height: 94, borderRadius: 11 }, info: { flex: 1, paddingHorizontal: 12 }, itemTitle: { color: '#27413a', fontSize: 14, fontWeight: '800', lineHeight: 19 }, location: { color: '#87958f', fontSize: 11, marginTop: 7 }, value: { color: '#173d35', fontSize: 14, fontWeight: '800', marginTop: 9 }, confirmed: { color: '#557d54', fontSize: 12 }, chevron: { color: '#9aa6a2', fontSize: 25, marginRight: 3 }, empty: { color: '#87958f', textAlign: 'center', marginTop: 60 } });
