import { StatusBar } from 'expo-status-bar';
import { Image, Linking, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuthSession } from '#/core/auth-session';
import { useRouter } from 'expo-router';
import { Text } from '#/components/ui/text';

export default function Profile() {
  const { authenticated, profile } = useAuthSession();
  const router = useRouter();
  const initials = (profile?.displayName || 'Guest User').split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase();
  return <SafeAreaView style={s.safe} edges={[]}><StatusBar style="dark" /><View style={s.topBar}><Text name="appTitle">Profile</Text></View><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.cover}><View style={s.coverCircle} /><Text style={s.coverWord}>FIND YOUR{`\n`}NEXT PLACE</Text></View>
    <View style={s.identityRow}><View style={s.avatar}>{profile?.accountPhoto ? <Image source={{ uri: profile.accountPhoto }} style={s.avatarImage} /> : <Text style={s.avatarText}>{initials}</Text>}</View><TouchableOpacity style={s.editButton} onPress={() => router.push('/(tabs)/profile/saved')}><Text style={s.editText}>Edit profile</Text></TouchableOpacity></View>
    <View style={s.details}><Text style={s.name}>{profile?.displayName || 'Guest User'}</Text><Text style={s.handle}>{profile?.neupId || profile?.neupidPrimary ? '@' + (profile.neupId || profile.neupidPrimary) : '@guest'}</Text><Text style={s.bio}>Exploring beautiful spaces and helping people find a place to call home.</Text><View style={s.metaRow}><Text style={s.meta}>⌖ Kathmandu, Nepal</Text><Text style={s.meta}>↗ alexhomes.com</Text></View><Text style={s.joined}>▣ NeupID: {profile?.neupId || profile?.neupidPrimary || 'guest'}</Text><View style={s.stats}><Text style={s.stat}><Text style={s.statStrong}>12</Text> Following</Text><Text style={s.stat}><Text style={s.statStrong}>48</Text> Followers</Text></View></View>
    {!authenticated && <TouchableOpacity style={s.authCard} activeOpacity={0.8} onPress={() => router.push('/auth')}><View style={s.authCopy}><Text style={s.authTitle}>Sign In / Sign Up for Better Experience.</Text><Text style={s.authSubtitle}>With Sign In, You can request visits and make inquiries.</Text></View><Text style={s.authChevron}>›</Text></TouchableOpacity>}
    <Text name="sectionTitle" style={s.sectionHeading}>Properties</Text><View style={s.leads}>{[['Listed Properties', 'Properties listed by you.'], ['My Properties', 'Properties owned by me.'], ['Saved Properties', 'Properties you saved for later.']].map(([title, subtitle], index) => <TouchableOpacity key={title} style={[s.leadCard, s.compactLeadCard, index === 0 && s.firstLeadCard, index === 2 && s.lastLeadCard, index < 2 && s.leadSeparator]} activeOpacity={0.8} onPress={() => title === 'Saved Properties' && router.push('/(tabs)/profile/saved')}><View style={s.leadIcon}><Text style={s.leadIconText}>⌂</Text></View><View style={s.leadCopy}><Text style={s.leadTitle}>{title}</Text><Text style={s.leadSubtitle}>{subtitle}</Text></View><Text style={s.leadChevron}>›</Text></TouchableOpacity>)}</View>
    <Text name="sectionTitle" style={s.sectionHeading}>Referrals</Text><View style={s.leads}>{[['My Referral Profile', 'Manage your referral details and rewards.', '/referrals/profile'], ['Leads referred by Me', 'View the leads you have referred.', '/referrals'], ['Post a new referral', 'Refer someone who is ready to move.', '/referrals/create']].map(([title, subtitle, route], index) => <TouchableOpacity key={title} style={[s.leadCard, s.compactLeadCard, index === 0 && s.firstLeadCard, index === 2 && s.lastLeadCard, index < 2 && s.leadSeparator]} activeOpacity={0.8} onPress={() => router.push(route as '/referrals' | '/referrals/profile' | '/referrals/create')}><View style={s.leadIcon}><Text style={s.leadIconText}>✦</Text></View><View style={s.leadCopy}><Text style={s.leadTitle}>{title}</Text><Text style={s.leadSubtitle}>{subtitle}</Text></View><Text style={s.leadChevron}>›</Text></TouchableOpacity>)}</View>
    <Text name="sectionTitle" style={s.sectionHeading}>Leads and Activities</Text><View style={s.leads}>{[['My Leads', 'See all the leads shared with you.'], ['Team Leads', 'See all the leads your team is working on.'], ['Base Leads', "See the base leads you've access to."]].map(([title, subtitle], index) => <TouchableOpacity key={title} style={[s.leadCard, s.compactLeadCard, index === 0 && s.firstLeadCard, index === 2 && s.lastLeadCard, index < 2 && s.leadSeparator]} activeOpacity={0.8}><View style={s.leadIcon}><Text style={s.leadIconText}>⌂</Text></View><View style={s.leadCopy}><Text style={s.leadTitle}>{title}</Text><Text style={s.leadSubtitle}>{subtitle}</Text></View><Text style={s.leadChevron}>›</Text></TouchableOpacity>)}</View>
    <Text name="sectionTitle" style={s.sectionHeading}>Account</Text><View style={s.leads}><TouchableOpacity style={[s.leadCard, s.compactLeadCard, s.firstLeadCard, s.leadSeparator]} activeOpacity={0.8} onPress={() => router.push('/profile/notofications')}><View style={s.leadIcon}><Text style={s.leadIconText}>♧</Text></View><View style={s.leadCopy}><Text style={s.leadTitle}>Notifications</Text><Text style={s.leadSubtitle}>Manage your notification preferences.</Text></View><Text style={s.leadChevron}>›</Text></TouchableOpacity><TouchableOpacity style={[s.leadCard, s.compactLeadCard, s.leadSeparator]} activeOpacity={0.8} onPress={() => Linking.openURL('https://neupgroup.com/account/security')}><View style={s.leadIcon}><Text style={s.leadIconText}>⌁</Text></View><View style={s.leadCopy}><Text style={s.leadTitle}>Security</Text><Text style={s.leadSubtitle}>Manage your account security.</Text></View><Text style={s.leadChevron}>↗</Text></TouchableOpacity><TouchableOpacity style={[s.leadCard, s.compactLeadCard, s.lastLeadCard]} activeOpacity={0.8} onPress={() => router.push('/auth/signout')}><View style={s.leadIcon}><Text style={s.leadIconText}>↪</Text></View><View style={s.leadCopy}><Text style={s.leadTitle}>Signout</Text><Text style={s.leadSubtitle}>Sign out of your NeupID account.</Text></View><Text style={s.leadChevron}>›</Text></TouchableOpacity></View>
  </ScrollView></SafeAreaView>;
}

const s = StyleSheet.create({
  safe:{flex:1,backgroundColor:'#fff'},content:{paddingBottom:28},topBar:{height:88,paddingTop:38,paddingHorizontal:20,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',elevation:12,shadowColor:'#173d35',shadowOffset:{width:0,height:6},shadowOpacity:0.24,shadowRadius:12,zIndex:10},cover:{height:154,backgroundColor:'#a9c8b4',overflow:'hidden',justifyContent:'center',paddingLeft:24},coverCircle:{position:'absolute',width:260,height:260,borderRadius:140,backgroundColor:'#6d9e88',right:-35,top:-115},coverWord:{color:'#fff',fontSize:25,fontWeight:'900',letterSpacing:2,lineHeight:29},identityRow:{height:74,paddingHorizontal:20,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},avatar:{width:88,height:88,borderRadius:44,backgroundColor:'#173d35',borderWidth:5,borderColor:'#fff',alignItems:'center',justifyContent:'center',marginTop:-38},avatarImage:{width:'100%',height:'100%',borderRadius:44},avatarText:{color:'#d6e3ca',fontWeight:'900',fontSize:25},editButton:{borderWidth:1.5,borderColor:'#cbd6d1',borderRadius:22,paddingHorizontal:20,paddingVertical:9},editText:{color:'#173d35',fontWeight:'800'},details:{paddingHorizontal:20},name:{color:'#142c27',fontSize:25,fontWeight:'900'},verified:{color:'#4c9b75'},handle:{color:'#70817c',fontSize:15,marginTop:2},bio:{color:'#29443d',fontSize:15,lineHeight:22,marginTop:17},metaRow:{flexDirection:'row',gap:18,marginTop:14,flexWrap:'wrap'},meta:{color:'#5f756d',fontSize:13},joined:{color:'#5f756d',fontSize:13,marginTop:11},stats:{flexDirection:'row',gap:22,marginTop:17},stat:{color:'#70817c',fontSize:14},statStrong:{color:'#173d35',fontWeight:'900'},sectionHeading:{color:'#173d35',fontSize:20,fontWeight:'900',marginHorizontal:20,marginTop:25,marginBottom:-4},authCard:{marginHorizontal:20,marginTop:20,padding:18,borderRadius:16,backgroundColor:'#eaf2e3',borderWidth:1,borderColor:'#d7e5d2',flexDirection:'row',alignItems:'center'},authCopy:{flex:1},authTitle:{color:'#173d35',fontSize:16,fontWeight:'900',lineHeight:21},authSubtitle:{color:'#557064',fontSize:12,lineHeight:18,marginTop:6},authChevron:{color:'#4c9b75',fontSize:28,marginLeft:12},leads:{marginTop:12},leadCard:{marginHorizontal:20,padding:15,backgroundColor:'#fff',borderWidth:1,borderColor:'#e3ebe6',flexDirection:'row',alignItems:'center'},firstLeadCard:{borderTopLeftRadius:16,borderTopRightRadius:16},lastLeadCard:{borderBottomLeftRadius:16,borderBottomRightRadius:16},leadSeparator:{borderBottomWidth:1,borderBottomColor:'#e3ebe6'},leadIcon:{width:42,height:42,borderRadius:13,backgroundColor:'#eaf2e3',alignItems:'center',justifyContent:'center'},leadIconText:{color:'#4c9b75',fontSize:21,fontWeight:'800'},leadCopy:{flex:1,marginLeft:12},leadTitle:{color:'#173d35',fontSize:15,fontWeight:'900'},leadSubtitle:{color:'#71817b',fontSize:12,lineHeight:17,marginTop:4},leadChevron:{color:'#9aa8a2',fontSize:25,marginLeft:10},
  compactLeadCard:{padding:11}, compactLeadIcon:{width:38,height:38,borderRadius:11}, compactLeadIconText:{fontSize:19}, compactLeadCopy:{marginLeft:11}, compactLeadTitle:{fontSize:14}, compactLeadSubtitle:{fontSize:11,lineHeight:16,marginTop:3}, compactLeadChevron:{fontSize:23,marginLeft:8}
});
