import { useState } from 'react';
import { useRouter } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { SafeAreaView } from 'react-native-safe-area-context';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { Text } from '#/components/ui/text';

const propertyTypes = ['House', 'Apartment', 'Land', 'Shop space'];

function Choice({ value, selected, onPress }: { value: string; selected: boolean; onPress: () => void }) {
  return <TouchableOpacity style={[styles.choice, selected && styles.choiceActive]} onPress={onPress} activeOpacity={0.8}><Text style={selected ? styles.choiceActiveText : styles.choiceText}>{value}</Text></TouchableOpacity>;
}

export default function NewProperty() {
  const router = useRouter();
  const [purpose, setPurpose] = useState('Sell');
  const [types, setTypes] = useState(['House']);

  const toggleType = (value: string) => setTypes((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]);

  return <SafeAreaView style={styles.page} edges={['top']}><StatusBar style="dark" /><View style={styles.header}><TouchableOpacity style={styles.headerBack} onPress={() => router.back()}><Text style={styles.back}>‹</Text><Text name="appTitle">Post Property</Text></TouchableOpacity><View style={styles.spacer} /></View><KeyboardAvoidingView style={styles.keyboard} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><View style={styles.stepRow}><Text style={styles.stepText}>STEP 1 OF 5</Text><Text style={styles.stepHint}>Property basics</Text></View><View style={styles.progressTrack}><View style={styles.progressFill} /></View><Text name="pageTitle" style={styles.title}>What are you posting?</Text><Text name="requirementsCardSubtitle" style={styles.intro}>Start with the basics so we can build the right listing for you.</Text><View style={styles.card}><Text style={styles.label}>I want to</Text><View style={styles.row}>{['Sell', 'Rent'].map((value) => <Choice key={value} value={value} selected={purpose === value} onPress={() => setPurpose(value)} />)}</View><View style={styles.typeLabelRow}><Text style={styles.label}>Property type</Text><Text style={styles.multiHint}>Select all that apply</Text></View><View style={styles.choices}>{propertyTypes.map((value) => <Choice key={value} value={value} selected={types.includes(value)} onPress={() => toggleType(value)} />)}</View><TouchableOpacity style={styles.button} onPress={() => {}}><Text style={styles.buttonText}>Continue</Text><Text style={styles.buttonArrow}>→</Text></TouchableOpacity></View></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#f4f7fb' }, keyboard: { flex: 1 }, header: { height: 88, paddingTop: 38, paddingHorizontal: 20, backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', elevation: 12, shadowColor: '#173d35', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.24, shadowRadius: 12, zIndex: 10 }, headerBack: { flexDirection: 'row', alignItems: 'center', gap: 8 }, back: { color: '#173d35', fontSize: 35, lineHeight: 35, marginTop: -3 }, spacer: { width: 24 }, content: { padding: 20, paddingBottom: 50 }, stepRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 7 }, stepText: { color: '#658b4f', fontSize: 11, letterSpacing: 1.5, fontWeight: '800' }, stepHint: { color: '#9aa6a2', fontSize: 11 }, progressTrack: { height: 5, backgroundColor: '#e1e9e4', borderRadius: 3, marginTop: 10, marginBottom: 28 }, progressFill: { width: '20%', height: 5, backgroundColor: '#87a873', borderRadius: 3 }, title: { marginTop: 8 }, intro: { marginTop: 6 }, card: { backgroundColor: '#fff', borderRadius: 16, padding: 16, marginTop: 24 }, label: { color: '#173d35', fontSize: 13, fontWeight: '800', marginBottom: 9 }, typeLabelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, multiHint: { color: '#9aa6a2', fontSize: 11, marginBottom: 9 }, row: { flexDirection: 'row', gap: 10, marginBottom: 20 }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 }, choice: { borderWidth: 1, borderColor: '#d7e1dc', borderRadius: 999, paddingHorizontal: 13, paddingVertical: 10 }, choiceActive: { backgroundColor: '#eaf2e3', borderColor: '#a9c59d' }, choiceText: { color: '#71817b', fontSize: 12, fontWeight: '700' }, choiceActiveText: { color: '#42604b', fontSize: 12, fontWeight: '800' }, button: { backgroundColor: '#173d35', borderRadius: 12, paddingVertical: 15, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 8 }, buttonText: { color: '#d8f36a', fontSize: 14, fontWeight: '800' }, buttonArrow: { color: '#d8f36a', fontSize: 18, marginTop: -2 } });
